#!/usr/bin/env python

#
# Portions of this script (the multipart form uploading) come from:
# http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/146306
#

from sys import argv, exit
from getopt import gnu_getopt
import magic
import httplib, urllib
from os import stat
from os.path import abspath,basename

boundary = '----------ThIs_Is_tHe_bouNdaRY_$'

#
#
#
def do_upload(host, file, metadata):
    st = stat(file)

    lines = []
    for (key, value) in metadata.items():
        lines.append('--' + boundary)
        lines.append('Content-Disposition: form-data; name="%s"' % key)
        lines.append('')
        lines.append(value)
    lines.append('--' + boundary)
    lines.append('Content-Disposition: form-data; name="file"; filename="%s"' % basename(file))
    lines.append('Content-Type: %s' % metadata['mimetype'])
    lines.append('')
    lines.append('')
    output = '\r\n'.join(lines)

    request = httplib.HTTPConnection(host)
    request.putrequest('POST', "/manage/create/")
    request.putheader('User-Agent', 'higgins-uploader')
    request.putheader('Content-Type', 'multipart/form-data; boundary=%s' % boundary)
    request.putheader('Content-Length', len(output) + st.st_size)
    request.endheaders()
    request.send(output)

    nread = len(output)
    f = open(file, 'rb')
    output = f.read(4096)
    request.send(output)
    nread += len(output)
    while not output == "":
        output = f.read(4096)
        request.send(output)
        nread += len(output)
    f.close()
    print "wrote %i bytes" % nread
    response = request.getresponse()
    print "Server returned status %s: %s" % (response.status,response.read())
    return response.status  

#
#
#
def do_local_upload(host, file, metadata):
    lines = []
    print "sending preamble.."
    for (key, value) in metadata.items():
        lines.append('--' + boundary)
        lines.append('Content-Disposition: form-data; name="%s"' % key)
        lines.append('')
        lines.append(value)
        print "form-data: '%s' => '%s' (%i bytes)" % (key,value,len(value))
    output = '\r\n'.join(lines)

    request = httplib.HTTPConnection(host)
    selector = "/manage/create/?is_local=true"
    request.putrequest('POST', selector)
    request.putheader('Content-Length', len(output))
    request.putheader('User-Agent', 'higgins-uploader')
    request.putheader('Content-Type', 'multipart/form-data; boundary=%s' % boundary)
    request.endheaders()
    request.send(output)
    response = request.getresponse()
    print "Server returned status %s: %s" % (response.status,response.read())
    return response.status  

#
#
#
def get_metadata(path, mimetype):
    metadata = { 'mimetype': mimetype }
    if mimetype == 'audio/mpeg':
        from mutagen import mp3
        tags = mp3.Open(path)
        metadata['artist'] = u''.join(tags['TPE1'].text)
        metadata['album'] = u''.join(tags['TALB'].text)
        metadata['title'] = u''.join(tags['TIT2'].text)
        metadata['genre'] = u''.join(tags['TCON'].text)
        metadata['length'] = str(int(tags.info.length*1000))
        metadata['bitrate'] = str(tags.info.bitrate)
        metadata['samplerate'] = str(tags.info.sample_rate)
        # hack to deal with TRCK tags formatted as numerator/denominator
        try:
            track_num = int(tags['TRCK'])
            metadata['track'] = u''.join(tags['TRCK'].text)
        except:
            a = str(tags['TRCK']).split('/')
            metadata['track'] = str(a[0])
        return metadata
    print "can't handle file with type %s" % mimetype
    return None

def print_help():
    print "Usage: higgins-upload [-h HOST] [-d] FILE..."
    print ""
    print "  -h HOST       The host to upload to.  Default is 'localhost:8000'"
    print "  -l            Enables local mode (File itself will not be uploaded)"
    print "  -v            Increase verbosity"
    print "  -q            Decrease verbosity"
    print ""

if __name__ == '__main__':
    host = 'localhost:8000'

    if len(argv) == 1:
        print_help()
        exit(1)
    opts,args = gnu_getopt(argv[1:], 'h:lvq')
    if len(args) == 0:
        print_help()
        exit(1)

    local_mode = False
    verbosity = 0
    for opt,arg in opts:
        if opt == '-h':
            host = arg
        if opt == '-l':
            local_mode = True
        if opt == '-v':
            verbosity = 1
        if opt == '-q':
            verbosity = -1
        
    cookie = magic.open(magic.MAGIC_MIME)
    if cookie.load('/usr/share/file/magic') == -1:
        print "Error: failed to load 'magic' database at /usr/share/file/magic"
        exit(1)
    print "========================================"
    for path in args:
        path = abspath(path)
        print "Reading meta-data from %s ..." % path
        mimetype = cookie.file(path)
        metadata = get_metadata(path, mimetype)
        if local_mode:
            metadata['local_path'] = path
        for datum in metadata.items():
            print "    %s: %s" % datum
        print "----------------------------------------"
        print "Uploading file to media server at %s ..." % host
        if local_mode:
            result = do_local_upload(host, path, metadata)
        else:
            result = do_upload(host, path, metadata)
        print "========================================"
    cookie.close()
    exit(0)
